# Generated by Django 3.2.3 on 2021-05-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='geolocation',
        ),
        migrations.AddField(
            model_name='customuser',
            name='lat',
            field=models.DecimalField(decimal_places=10, default=27.7172, max_digits=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lng',
            field=models.DecimalField(decimal_places=10, default=85.324, max_digits=15),
        ),
    ]
