# Generated by Django 3.2.3 on 2021-06-14 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('alias', models.SlugField(max_length=200, unique=True)),
                ('fulltext', models.TextField(null=True)),
                ('metakey', models.TextField(blank=True, null=True, verbose_name='Meta Key')),
                ('metadesc', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='BlogImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='blog/static/blog')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.IntegerField(blank=True, default=0)),
                ('right', models.IntegerField(blank=True, default=0)),
                ('level', models.IntegerField(blank=True, default=0)),
                ('title', models.CharField(max_length=200)),
                ('alias', models.SlugField(max_length=200)),
                ('note', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('checked_out_at', models.DateTimeField(auto_now=True)),
                ('metadesc', models.TextField(blank=True, verbose_name='Meta Description')),
                ('metakey', models.TextField(blank=True, verbose_name='Meta Key')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('checked_out_by', models.ForeignKey(blank=True, db_column='checked_out_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_checked_out_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(db_column='modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_modified_by', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('alias', models.SlugField(max_length=200, unique=True)),
                ('introtext', models.CharField(blank=True, max_length=200, null=True, verbose_name='Intro Text')),
                ('displayphoto', models.ImageField(blank=True, null=True, upload_to='blog/static/blog', verbose_name='Display Photo')),
                ('research_data', models.TextField(default='Research Data')),
                ('fulltext', models.TextField(blank=True, null=True, verbose_name='Full Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('checked_out_time', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('researched', models.BooleanField(default=False, verbose_name='Research completed')),
                ('authored', models.BooleanField(default=False, verbose_name='Authoring completed')),
                ('edited', models.BooleanField(default=False, verbose_name='Editing completed')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('metakey', models.TextField(blank=True, null=True, verbose_name='Meta Key')),
                ('metadesc', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('hits', models.IntegerField(blank=True, default=0)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('featured', models.BooleanField(blank=True, default=False, null=True)),
                ('authored_by', models.ForeignKey(db_column='authored_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_authored_by', to=settings.AUTH_USER_MODEL)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blogs.category', verbose_name='Category')),
                ('checked_out_by', models.ForeignKey(blank=True, db_column='checked_out_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_checked_out_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_created_by', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(db_column='edited_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_edited_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(db_column='modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_modified_by', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(db_column='published_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_published_by', to=settings.AUTH_USER_MODEL)),
                ('researched_by', models.ForeignKey(db_column='researched_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_researched_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
